name 'ericsson-swap'
version '0.1.0'
source 'ssh://gerrit.ericsson.se:29418/puppet/puppet-module-swap'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'Module to manage swap'
description 'Module to manage swap'
project_page ''

dependency 'puppetlabs/stdlib', '>= 3.2.0'
